### ISSUE TITLE
Nagios HTTP Checks return 403

### ISSUE THREAD

**Issue by one-t** [dfederlein/ansible-demos#3]
The Nagios HTTP checks are misconfigured and return a warning

![image](https://user-images.githubusercontent.com/28987580/38346960-4cb18bc0-3866-11e8-81b0-d0c6a0693569.png)

**Comment by one-t** [comment]
Nagios checks are configured with the vagrant internal IP, the external IP works correctly when used with the check_http command directly.

```
[vagrant@demovm4 ~]$ /usr/lib64/nagios/plugins/check_http -H 172.16.2.6 -e 'HTTP'
HTTP OK: Status line output matched "HTTP" - HTTP/1.1 200 OK - 380 bytes in 0.003 second response time |time=0.002939s;;;0.000000 size=380B;;;0


[vagrant@demovm4 ~]$ /usr/lib64/nagios/plugins/check_http -H 10.0.2.15 -e 'HTTP'
HTTP OK: Status line output matched "HTTP" - HTTP/1.1 403 Forbidden - 5179 bytes in 0.001 second response time |time=0.001159s;;;0.000000 size=5179B;;;0
```

**Comment by dfederlein** [comment]
Hey Mat,

I just caught these as I was adapting this to work with cent or rhel as needed.  I'll review and merge/comment as I can over the week.

**Comment by dfederlein** [comment]
I wonder if we should just use the "external" ip and fix the vagrant networking on each host to remove the default route out of the "internal" ip.

I've done this in a fork of the project I need to PR back up to this, where I actually do a search for eth0 on cent and (whatever rhel is naming their things now) and pull out how many routes that interface has and pull the default route for the 10 network. we could then use ansible_ssh_host on everything and just use external IPs.

Thoughts?

**Comment by dfederlein** [comment]
Oh duh, I just realized what I was misreading.

Yes, let's change the template to use the external IP.  let me dig through this demo and get that done.

**Comment by dfederlein** [comment]
Isn't this solved with your PR using ansible_ssh_host instead of the eth0.address?

If so I'll close it out.

**Comment by one-t** [comment]
Hey, David- not sure, it's been a little bit since I looked at this so I
don't quite recall... will have to try it out

MAT WILSON

Architect - AUTOMATION PRACTICE

RHCSA/RHCSAA

Red Hat Consulting Services <https://www.redhat.com/>

mawilson@redhat.com    M: 949-413-8941
<https://red.ht/sig>
TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>
@redhatnews <https://twitter.com/redhatnews>   Red Hat
<https://www.linkedin.com/company/red-hat>   Red Hat
<https://www.facebook.com/RedHatInc>

**Comment by dfederlein** [comment]
Thanks Mat, let me know what you think we should do here. I'm open to tweaks.
